#!/usr/bin/env bash

# if anything happens, get out
set -ex

# do stuff
apt-get update
dpkg-query -W -f='${Package}\n' > /tmp/a.txt
apt-get install -y python3-pip python3-dev build-essential
pip3 install setuptools wheel
pip3 install -r /tmp/requirements.txt
ln -s /usr/bin/python3 /usr/local/bin/python
dpkg-query -W -f='${Package}\n' > /tmp/b.txt
apt-get remove -y `diff --changed-group-format='%>' --unchanged-group-format='' /tmp/a.txt /tmp/b.txt | xargs`
apt-get autoclean -y
apt-get autoremove -y
rm -rf /var/lib/apt/lists/*
rm -rf /var/cache/apt/* /tmp/a.txt /tmp/b.txt
