#!/usr/bin/env bash

# if anything happens, get out
set -e

if [ "$#" -ne 1 ]; then
    echo "ERROR: Illegal number of parameters for install-ffmpeg. Expected ARCH."
    exit 1
fi

ARCH=$1
ffarch="ARCH_NOT_SUPPORTED"

if [ "$ARCH" = "amd64" ]; then
    ffarch="amd64"
elif [ "$ARCH" = "arm32v7" ]; then
    ffarch="armhf"
elif [ "$ARCH" = "arm64v8" ]; then
    ffarch="arm64"
fi

ffurl="https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-${ffarch}-static.tar.xz"

mkdir -p /usr/local/ffmpeg
curl -sSL "${ffurl}" | tar xJvf - -C /usr/local/ffmpeg/ --strip 1
